### ISSUE TITLE
Should make more clear that "preview" is potentially destructive

### ISSUE THREAD

**Issue by otherjoel** [lijunsong/pollen-rock#12]
It's not immediately obvious to the user—and perhaps it _should_ be made obvious somehow—that previewing the file also saves/overwrites it with the current editor contents. This makes previewing potentially a destructive operation, which is generally not expected!  Having auto-preview on increases the danger of losing data.

**Comment by lijunsong** [comment]
Agreed. I haven't come up with a plan to make rendering an isolated operation.

**Comment by lijunsong** [comment]
In next release, there will be no "preview." Preview is a misleading word (in terms of how it works).

"Render" and "Autorender" are probably better words to use in this context.

**Comment by lijunsong** [comment]
Fix in.
