### ISSUE TITLE
How to run a local copy for development

### ISSUE THREAD

**Issue by jameskolce** [lijunsong/pollen-rock#27]
Hi @lijunsong, I would like to try some things on the editor, however, I don't have experience with Racket, so I'm was wondering how can I run a local copy of pollen-rock where I can see the changes that I make.

Thanks!

**Comment by lijunsong** [comment]
On which step you feel stuck?

**Comment by jameskolce** [comment]
I was completely lost after cloning the repository and didn't know where to start. However, I just read this https://blog.racket-lang.org/2017/10/tutorial-creating-a-package.html and `raco pkg install` is what I was looking for… sorry for opening an issue before doing a bit of research.

I am planning to start a blog using Pollen, and I think this project could help me, I just think the editor could be improved. I have absolutely no experience with Racket, but I do have with HTML/CSS/JS so I'll work on that. I'll keep my fork here on Github, so if at some point you like my changes, I'm willing to contribute to this project!

Thanks.

**Comment by jameskolce** [comment]
I just noticed the new editor in the `dev` branch being written in Elm, and that's what I was actually planning to do. But I'm having trouble using it; I already installed all the dependencies (both for Node and Elm) and started the client and the api, however I'm not able to access `ttybook.local` so I'm assuming the alternative is `http://localhost:8001/`, when I open that address I see the *Polen Rock Editor* page but it says `not found` and:

<img width="970" alt="imagen" src="https://user-images.githubusercontent.com/2559808/33691861-9f09fcd0-daa7-11e7-9f98-f098cf794f90.png">

Any ideas?

**Comment by jameskolce** [comment]
I got everything running but just noticed that the Elm implementation is incomplete. I'll close this and open a new one with something different

**Comment by lijunsong** [comment]
I'll address your questions in the newly opened issues.
